version: '3'
services:

  go-api-example-db:
    container_name: go-api-example-db
    image: mysql:5.6
    ports:
      - "33061:3306"
    environment:
      - "MYSQL_DATABASE=users_db"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=Admin.123"
      - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  go-api-example:
    container_name: go-api-example
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: golang:go-api-example
    links:
      - go-api-example-db:go-api-example-db
    ports:
      - "8083:8083"
    tty: true